export const FETCH_PLAYLIST_ITEM_LIST_ERROR = 'FETCH_PLAYLIST_ITEM_LIST_ERROR';
export const FETCH_PLAYLIST_ITEM_LIST_SUCCESS =
  'FETCH_PLAYLIST_ITEM_LIST_SUCCESS';
export const FETCH_PLAYLIST_ITEM_LIST_LOADING =
  'FETCH_PLAYLIST_ITEM_LIST_LOADING';

export const FETCH_TRACK_ITEM_LIST_ERROR = 'FETCH_TRACK_ITEM_LIST_ERROR';
export const FETCH_TRACK_ITEM_LIST_SUCCESS = 'FETCH_TRACK_ITEM_LIST_SUCCESS';
export const FETCH_TRACK_ITEM_LIST_LOADING = 'FETCH_TRACK_ITEM_LIST_LOADING';

export const FETCH_GENRE_ITEM_LIST_ERROR = 'FETCH_GENRE_ITEM_LIST_ERROR';
export const FETCH_GENRE_ITEM_LIST_SUCCESS = 'FETCH_GENRE_ITEM_LIST_SUCCESS';
export const FETCH_GENRE_ITEM_LIST_LOADING = 'FETCH_GENRE_ITEM_LIST_LOADING';

export const MUSIC_PLAYER_PLAY = 'MUSIC_PLAYER_PLAY';
export const MUSIC_PLAYER_PAUSE = 'MUSIC_PLAYER_PAUSE';
export const MUSIC_PLAYER_FORWARD = 'MUSIC_PLAYER_FORWARD';
export const MUSIC_PLAYER_BACKWARD = 'MUSIC_PLAYER_BACKWARD';
export const MUSIC_PLAYER_REPEAT_TOGGLE = 'MUSIC_PLAYER_REPEAT_TOGGLE';
export const MUSIC_PLAYER_SEEK = 'MUSIC_PLAYER_SEEK';
export const MUSIC_PLAYER_SET_TIME = 'MUSIC_PLAYER_SET_TIME';
export const MUSIC_PLAYER_SET_DURATION = 'MUSIC_PLAYER_SET_DURATION';
export const MUSIC_PLAYER_ERROR = 'MUSIC_PLAYER_ERROR';
export const MUSIC_PLAYER_MUTE_TOGGLE = 'MUSIC_PLAYER_MUTE_TOGGLE';
